substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: basement_fan
  friendly_name: Basement Fan
  ip_address: !secret basement_fan_ip


esphome:
  # https://esphome.io/components/esphome
  name: $device_name
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout
  

wifi:
  # https://esphome.io/components/wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: $ip_address
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns1

    
# web_server:
#   port: 80
  # https://esphome.io/components/web_server.html


logger:
  # https://esphome.io/components/logger


api:
  # password: !secret esphome_api_password
  # https://esphome.io/components/api


ota:
  password: !secret esphome_ota_password
  # https://esphome.io/components/ota


# https://esphome.io/devices/sonoff_basic.html
binary_sensor:
  - platform: gpio
    # https://esphome.io/components/binary_sensor/gpio.html
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    name: $friendly_name Button
    on_press:
      - switch.toggle: relay_template
    internal: True


switch:
  - platform: gpio
    pin: GPIO12
    id: relay

  # tie the led & relay together & report status regarless of trigger method   
  - platform: template
    # https://esphome.io/components/switch/template.html
    name: $friendly_name
    id: relay_template
    lambda: |-
      if (id(relay).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - light.turn_on: status_led
      - switch.turn_on: relay
    turn_off_action:
      - light.turn_off: status_led
      - switch.turn_off: relay


output:
  - platform: esp8266_pwm
    # https://esphome.io/components/output/esp8266_pwm.html
    id: green_led_output
    pin:
      number: GPIO13
      inverted: True


light:
  - platform: monochromatic
    # https://esphome.io/components/light/monochromatic.html
    name: $friendly_name LED
    output: green_led_output
    id: status_led
    default_transition_length: 1ms # controls the light fade/transition time
    internal: True
