substitutions:
  # https://esphome.io/guides/configuration-types.html#substitutions
  device_name: sonoff_basic
  friendly_name: Sonoff Basic
  ip_address: !secret sonoff_basic_ip
  icon: "mdi:flash-circle"


esphome:
  # https://esphome.io/components/esphome
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout


wifi:
  # https://esphome.io/components/wifi
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${ip_address}
    gateway: !secret wifi_gateway
    subnet: !secret wifi_subnet
    dns1: !secret wifi_dns1


# web_server:
#   port: 80
#   # https://esphome.io/components/web_server.html


logger:
  # https://esphome.io/components/logger


api:
  password: !secret esphome_api_password
  # https://esphome.io/components/api


ota:
  password: !secret esphome_ota_password
  # https://esphome.io/components/ota


# https://esphome.io/devices/sonoff_basic.html
binary_sensor:
  - platform: gpio
    # https://esphome.io/components/binary_sensor/gpio.html
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    id: button
    name: ${friendly_name} Button
    on_press:
      - switch.toggle: relay
    internal: True


switch:
  - platform: gpio
    # https://esphome.io/components/switch/gpio
    id: led
    name: ${friendly_name} LED
    pin:
      number: GPIO13
      inverted: True
    internal: True

  - platform: gpio
    # https://esphome.io/components/switch/gpio
    pin: GPIO12
    id: relay
    name: ${friendly_name}
    icon: ${icon}
    on_turn_on:
    - switch.turn_on: led
    on_turn_off:
    - switch.turn_off: led
